name: Manual Build and Deploy

# This workflow is now triggered manually from the Actions tab
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version tag to create (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-deploy:
    name: Build, Deploy to Repo, and Release
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --security-opt seccomp=unconfined
    
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Using the more complete dependency list from your previous build to prevent errors.
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed \
            base-devel git gtk3 nss alsa-lib xdg-utils libxss libcups \
            ttf-liberation libpulse libva desktop-file-utils hicolor-icon-theme \
            fontconfig libjpeg-turbo flac libwebp minizip opus harfbuzz \
            libxslt libpng freetype2

      - name: Set correct permissions for makepkg
        run: |
          useradd -m builduser
          chown -R builduser:builduser .

      - name: Build the package as builduser
        run: sudo -u builduser makepkg -sf --noconfirm

      - name: Get package filename
        id: get_filename
        run: echo "PKG_NAME=$(basename *.pkg.tar.zst)" >> $GITHUB_ENV
      
      - name: Checkout pacman repo
        uses: actions/checkout@v4
        with:
          repository: 'n3ptune-plan3t/custom-arch-repo'
          ref: 'main'
          path: 'repo'
          token: ${{ secrets.MY_REPO_PAT }}

      - name: Update Arch repository
        run: |
          mkdir -p repo/x86_64
          mv ${{ env.PKG_NAME }} repo/x86_64/
          # Fixed the stray parenthesis in this command
          repo-add repo/custom-arch-repo.db.tar.gz repo/x86_64/${{ env.PKG_NAME }}
          
      - name: Commit and push repository changes
        run: |
          cd repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update repository: add ${{ env.PKG_NAME }}"
            git push
          else
            echo "No changes to the repository to commit."
          fi
          cd ..

      # NEW: This step creates the Git tag based on your input
      - name: Create and push Git tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      # MODIFIED: This step now uses your input to create the release
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          # Use the version provided in the manual trigger as the tag name
          tag_name: ${{ github.event.inputs.version }}
          files: "repo/x86_64/${{ env.PKG_NAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
